name: Run Data Update Weekly

# run every week on Tuesday at 00:00 UTC
on:
  schedule:
    - cron: '30 0 * * 2'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Run the script
      run: |
        python docs/generate_past_seminar_html.py
        python docs/generate_upcoming_seminar_html.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated data transfer" || echo "No changes to commit"
        git push

